name: XML to JSON Conversion and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  xml-to-json-and-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Convert XML to JSON
        run: npm run convert-xml-to-json
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          project-key: my-project-key
          project-name: My Project Name
          organization: my-organization
          scanner-properties: |
            sonar.sources=.
            sonar.exclusions=node_modules/**/*,test/**/*
            sonar.javascript.lcov.reportPaths=coverage/lcov.info
