on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Convert XML to JSON
        run: npm run convert-xml-to-json
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          scanner-properties: |
              sonar.sources=.
              sonar.exclusions=node_modules/**/*,test/**/*
              sonar.javascript.lcov.reportPaths=coverage/lcov.info
